-- =============================================================================
-- ONLINE RETAIL II ANALYTICS — REVENUE & BUSINESS ANALYSIS SQL
-- File: 05_revenue_analysis.sql
-- Purpose: Macro revenue analysis, time-series growth, geographic distribution,
--          AOV, cancellation impact, and segment contribution.
-- Database: online_retail_analytics
-- =============================================================================

USE online_retail_analytics;

-- -----------------------------------------------------------------------------
-- 1. MACRO EXECUTIVE REVENUE OVERVIEW
-- Summarizes overall financial performance, orders, customers, and AOV.
-- Target Revenue: £20,476,034.43
-- Target Orders: 40,067
-- -----------------------------------------------------------------------------
SELECT 
    ROUND(SUM(Revenue), 2) AS TotalCompletedRevenue,
    COUNT(DISTINCT InvoiceNo) AS TotalCompletedOrders,
    COUNT(DISTINCT CustomerID) AS IdentifiedPurchasingCustomers,
    ROUND(SUM(Revenue) / COUNT(DISTINCT InvoiceNo), 2) AS AverageOrderValue
FROM retail_transactions
WHERE IsCancelled = 0 AND Quantity > 0 AND UnitPrice > 0;


-- -----------------------------------------------------------------------------
-- 2. ANNUAL REVENUE BREAKDOWN
-- Compares revenue performance across 2009, 2010, and 2011.
-- -----------------------------------------------------------------------------
SELECT 
    Year,
    COUNT(DISTINCT InvoiceNo) AS CompletedOrders,
    COUNT(DISTINCT CustomerID) AS ActiveCustomers,
    ROUND(SUM(Revenue), 2) AS AnnualRevenue,
    ROUND(SUM(Revenue) * 100.0 / (SELECT SUM(Revenue) FROM retail_transactions WHERE IsCancelled = 0), 2) AS AnnualRevenueContributionPct
FROM retail_transactions
WHERE IsCancelled = 0 AND Quantity > 0 AND UnitPrice > 0
GROUP BY Year
ORDER BY Year;


-- -----------------------------------------------------------------------------
-- 3. QUARTERLY REVENUE TRENDS
-- Breaks down financial metrics by Year and Quarter.
-- -----------------------------------------------------------------------------
SELECT 
    Quarter,
    COUNT(DISTINCT InvoiceNo) AS Orders,
    COUNT(DISTINCT CustomerID) AS UniqueCustomers,
    ROUND(SUM(Revenue), 2) AS QuarterlyRevenue,
    ROUND(SUM(Revenue) / COUNT(DISTINCT InvoiceNo), 2) AS QuarterlyAOV
FROM retail_transactions
WHERE IsCancelled = 0 AND Quantity > 0 AND UnitPrice > 0
GROUP BY Quarter
ORDER BY Quarter;


-- -----------------------------------------------------------------------------
-- 4. MONTH-OVER-MONTH (MoM) REVENUE GROWTH RATE
-- Uses LAG() window function to calculate monthly revenue differences and % growth.
-- -----------------------------------------------------------------------------
WITH MonthlyRevenue AS (
    SELECT 
        YearMonth,
        Year,
        Month,
        COUNT(DISTINCT InvoiceNo) AS TotalOrders,
        ROUND(SUM(Revenue), 2) AS CurrentMonthRevenue
    FROM retail_transactions
    WHERE IsCancelled = 0 AND Quantity > 0 AND UnitPrice > 0
    GROUP BY YearMonth, Year, Month
)
SELECT 
    YearMonth,
    TotalOrders,
    CurrentMonthRevenue,
    LAG(CurrentMonthRevenue, 1) OVER (ORDER BY YearMonth) AS PriorMonthRevenue,
    ROUND(CurrentMonthRevenue - LAG(CurrentMonthRevenue, 1) OVER (ORDER BY YearMonth), 2) AS RevenueMoMChange,
    ROUND(
        (CurrentMonthRevenue - LAG(CurrentMonthRevenue, 1) OVER (ORDER BY YearMonth)) * 100.0 / 
        LAG(CurrentMonthRevenue, 1) OVER (ORDER BY YearMonth), 
        2
    ) AS RevenueMoMGrowthPct
FROM MonthlyRevenue
ORDER BY YearMonth;


-- -----------------------------------------------------------------------------
-- 5. GEOGRAPHIC REVENUE & CUSTOMER DISTRIBUTION (TOP 10 COUNTRIES)
-- Evaluates revenue contribution, orders, customers, and AOV by country.
-- -----------------------------------------------------------------------------
SELECT 
    Country,
    COUNT(DISTINCT InvoiceNo) AS TotalOrders,
    COUNT(DISTINCT CustomerID) AS TotalCustomers,
    ROUND(SUM(Revenue), 2) AS TotalCountryRevenue,
    ROUND(SUM(Revenue) * 100.0 / (SELECT SUM(Revenue) FROM retail_transactions WHERE IsCancelled = 0), 2) AS CountryRevenuePct,
    ROUND(SUM(Revenue) / COUNT(DISTINCT InvoiceNo), 2) AS CountryAOV
FROM retail_transactions
WHERE IsCancelled = 0 AND Quantity > 0 AND UnitPrice > 0
GROUP BY Country
ORDER BY TotalCountryRevenue DESC
LIMIT 10;


-- -----------------------------------------------------------------------------
-- 6. REPEAT CUSTOMER VS. ONE-TIME CUSTOMER REVENUE CONTRIBUTION
-- CTE grouping revenue impact generated by repeat buyers vs single-order buyers.
-- -----------------------------------------------------------------------------
WITH CustomerOrderMetrics AS (
    SELECT 
        CustomerID,
        COUNT(DISTINCT InvoiceNo) AS OrderCount,
        SUM(Revenue) AS TotalSpend
    FROM retail_transactions
    WHERE CustomerID IS NOT NULL AND IsCancelled = 0
    GROUP BY CustomerID
)
SELECT 
    CASE WHEN OrderCount > 1 THEN 'Repeat Customers (>1 Order)' ELSE 'One-Time Customers (1 Order)' END AS CustomerGroup,
    COUNT(*) AS CustomerCount,
    ROUND(SUM(TotalSpend), 2) AS TotalGroupRevenue,
    ROUND(SUM(TotalSpend) * 100.0 / (SELECT SUM(Revenue) FROM retail_transactions WHERE CustomerID IS NOT NULL AND IsCancelled = 0), 2) AS RevenuePctOfIdentified
FROM CustomerOrderMetrics
GROUP BY CASE WHEN OrderCount > 1 THEN 'Repeat Customers (>1 Order)' ELSE 'One-Time Customers (1 Order)' END;


-- -----------------------------------------------------------------------------
-- 7. MONTHLY CANCELLATION RATE TREND
-- Tracks order line cancellation counts and rates over time.
-- -----------------------------------------------------------------------------
SELECT 
    YearMonth,
    COUNT(*) AS TotalTransactionLines,
    SUM(CASE WHEN IsCancelled = 1 THEN 1 ELSE 0 END) AS CancelledLines,
    SUM(CASE WHEN IsCancelled = 0 THEN 1 ELSE 0 END) AS CompletedLines,
    ROUND(SUM(CASE WHEN IsCancelled = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS MonthlyCancellationRatePct
FROM retail_transactions
GROUP BY YearMonth
ORDER BY YearMonth;
